"""Public feature boundary for canonical code identity."""

from infinity_context_core.features.code_identity.application import (
    CodeRepositoryResolutionMethod,
    RegisterCodeScopeAuthorizationCommand,
    RegisterCodeScopeAuthorizationHandler,
    RegisterCodeScopeAuthorizationResult,
    ResolveCodeRepositoryCommand,
    ResolveCodeRepositoryHandler,
    ResolveCodeRepositoryResult,
)
from infinity_context_core.features.code_identity.domain import (
    FEATURE_ID,
    CodeIdentityFeature,
    CodeRepository,
    CodeRepositoryProvider,
    CodeRepositoryStatus,
    CodeScope,
    CodeScopeAuthorization,
    CodeScopeAuthorizationStatus,
    CodeScopeDescriptor,
    CodeScopeEnvironment,
    CodeScopeLevel,
    CodeWorktreeState,
    RepositoryEvidenceKind,
    RepositoryIdentityEvidence,
)
from infinity_context_core.features.code_identity.ports import (
    CodeRepositoryClockPort,
    CodeRepositoryIdPort,
    CodeRepositoryPort,
    CodeScopeAuthorizationIdPort,
    CodeScopeAuthorizationPort,
)

__all__ = (
    "FEATURE_ID",
    "CodeIdentityFeature",
    "CodeRepository",
    "CodeRepositoryClockPort",
    "CodeRepositoryIdPort",
    "CodeRepositoryPort",
    "CodeRepositoryProvider",
    "CodeRepositoryResolutionMethod",
    "CodeRepositoryStatus",
    "CodeScope",
    "CodeScopeDescriptor",
    "CodeScopeAuthorization",
    "CodeScopeAuthorizationIdPort",
    "CodeScopeAuthorizationPort",
    "CodeScopeAuthorizationStatus",
    "CodeScopeEnvironment",
    "CodeScopeLevel",
    "CodeWorktreeState",
    "RepositoryEvidenceKind",
    "RepositoryIdentityEvidence",
    "RegisterCodeScopeAuthorizationCommand",
    "RegisterCodeScopeAuthorizationHandler",
    "RegisterCodeScopeAuthorizationResult",
    "ResolveCodeRepositoryCommand",
    "ResolveCodeRepositoryHandler",
    "ResolveCodeRepositoryResult",
)
