"""Ports owned by the context_building feature."""

from infinity_context_core.features.context_building.ports.candidates import (
    CanonicalContextHydratorPort,
    ContextCandidateHitProviderPort,
    ContextCandidateProviderPort,
    ContextCandidateRequest,
    ContextClockPort,
)
from infinity_context_core.features.context_building.ports.locator_retrieval import (
    CanonicalLocatorHydratorPort,
    CanonicalLocatorReadPort,
    LocatorCandidateProviderPort,
)
from infinity_context_core.features.context_building.ports.retrieval_profile_lifecycle import (
    CanonicalProjectionItem,
    CanonicalProjectionPage,
    CanonicalProjectionSourcePort,
    ExactVersionDeletionProof,
    InstalledReleaseIdentity,
    ProfileAttestationCheckpoint,
    ProfileAttestationPageReceipt,
    ProfileCleanup,
    ProfileCollectionDeleteAuthorization,
    ProfileQueryAdmission,
    ProfileQueryAdmissionStatus,
    ProfileReconciliationOperation,
    ProfileReconciliationWriteOutcome,
    ProfileTombstoneDeleteAuthorization,
    ProjectedGenerationObservation,
    RetrievalProfileCollectionCleanupPort,
    RetrievalProfileDiagnosticsPort,
    RetrievalProfileProjectionPort,
    RetrievalProfileRegistryPort,
    RetrievalProfileRetirementPort,
    RuntimeFenceOwner,
)

__all__ = (
    "CanonicalContextHydratorPort",
    "ContextCandidateHitProviderPort",
    "ContextCandidateProviderPort",
    "ContextCandidateRequest",
    "ContextClockPort",
    "CanonicalLocatorHydratorPort",
    "CanonicalLocatorReadPort",
    "LocatorCandidateProviderPort",
    "CanonicalProjectionItem",
    "CanonicalProjectionPage",
    "CanonicalProjectionSourcePort",
    "ExactVersionDeletionProof",
    "InstalledReleaseIdentity",
    "ProfileAttestationCheckpoint",
    "ProfileAttestationPageReceipt",
    "ProfileReconciliationOperation",
    "ProfileReconciliationWriteOutcome",
    "ProfileQueryAdmission",
    "ProfileQueryAdmissionStatus",
    "RuntimeFenceOwner",
    "ProfileCleanup",
    "ProfileCollectionDeleteAuthorization",
    "ProfileTombstoneDeleteAuthorization",
    "ProjectedGenerationObservation",
    "RetrievalProfileCollectionCleanupPort",
    "RetrievalProfileDiagnosticsPort",
    "RetrievalProfileProjectionPort",
    "RetrievalProfileRegistryPort",
    "RetrievalProfileRetirementPort",
)
