from __future__ import annotations

import ast
import asyncio
import importlib.util
import io
import os
import re
import tarfile
import zipfile
from pathlib import Path
from types import SimpleNamespace

import pytest
from infinity_context_core.ports.adapters import VectorWriteResult
from infinity_context_server.composition import Container
from infinity_context_server.processes.outbox import ClaimedOutboxJob
from infinity_context_server.processes.projections import (
    OutboxProjectionError,
    ProjectionOutboxProcess,
)

import tests.architecture.retrieval_archive_guard as archive_guard
from tests.architecture.retrieval_archive_guard import (
    ArchiveSourceGuardError,
    inspect_source_archive,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
CORE_FEATURE = (
    REPO_ROOT
    / "packages"
    / "infinity_context_core"
    / "infinity_context_core"
    / "features"
    / "context_building"
)
SERVER_PACKAGE = REPO_ROOT / "packages" / "infinity_context_server" / "infinity_context_server"
SERVER_CONTEXT_BUILDING = SERVER_PACKAGE / "features" / "context_building"
ADAPTERS_PACKAGE = (
    REPO_ROOT / "packages" / "infinity_context_adapters" / "infinity_context_adapters"
)
POSTGRES_ADAPTER = ADAPTERS_PACKAGE / "postgres"
QDRANT_ADAPTER = ADAPTERS_PACKAGE / "qdrant"
PRODUCTION_PACKAGE_ROOTS = tuple((REPO_ROOT / "packages").glob("*/"))
CURRENT_SOURCE_ROOTS = (REPO_ROOT,)
EXPLICIT_NON_SOURCE_DIRECTORIES = {
    Path(".git"): "repository metadata",
    Path(".pytest_cache"): "generated test cache",
    Path(".ruff_cache"): "generated lint cache",
    Path(".venv"): "resolved third-party environment",
}
EXPLICIT_NON_SOURCE_DIRECTORY_NAMES = {
    "__pycache__": "generated bytecode cache",
    "node_modules": "resolved third-party JavaScript dependencies",
}
VERSIONED_RETRIEVAL_PATH_ALLOWLIST: set[Path] = set()
OLD_RETRIEVAL_IDENTIFIER = re.compile(
    r"(?:RetrievalV2|RetrieveContextV2|ContextRetrieval\w*V2|"
    r"(?:Canonical|Postgres)?Locator\w*V2|retrieve_context_v2|"
    r"locator_retrieval_v2|retrieval_v2)"
)
OLD_SERVING_MODULE = "infinity_context_server.serving_identity"
REMOVED_RETRIEVAL_MODULE = "infinity_context_server.retrieval_composition"
REMOVED_PROJECTION_MODULE = "infinity_context_adapters.postgres.locator_projection_maintenance"
REMOVED_PROJECTION_NAMES = {
    "locator_projection_maintenance",
    "locator_vector_index",
}
CURRENT_V2_NAME = re.compile(
    r"(?:[a-z0-9]+[_-])*(?:locator|retrieval)[ _-]v2"
    r"(?:[_-][a-z0-9{}]+)*",
    re.IGNORECASE,
)
TEXT_SUFFIXES = {
    ".cjs",
    ".cts",
    ".js",
    ".json",
    ".md",
    ".mjs",
    ".mts",
    ".py",
    ".pyi",
    ".rst",
    ".toml",
    ".ts",
    ".tsx",
    ".sh",
    ".yaml",
    ".yml",
}
IMMUTABLE_V2_PATHS = {
    *(
        Path("packages/infinity_context_adapters/infinity_context_adapters/postgres/migrations")
        / name
        for name in (
            "0039_locator_retrieval_attributes.sql",
            "0040_locator_profile_lifecycle.sql",
            "0041_locator_profile_attestation_fence.sql",
            "0042_locator_profile_retirement.sql",
            "0043_locator_profile_transition_audit.sql",
            "0044_locator_profile_operator_receipts.sql",
            "0046_locator_profile_linearizable_fences.sql",
        )
    ),
}
IMMUTABLE_WIRE_PATH_PREFIXES = (
    Path(
        "packages/infinity_context_contracts/infinity_context_contracts/fixtures/context_retrieval_v2"
    ),
    Path("packages/infinity_context_ts_sdk/fixtures/context_retrieval_v2"),
)
IMMUTABLE_COMPATIBILITY_LITERALS = {
    "context-retrieval.v2",
    "context-retrieval-v2-cases.v1",
    "context-retrieval-v2-errors.v1",
    "context-retrieval-v2-hostile-responses.v1",
    "context-retrieval-v2-transport-outcomes.v1",
    "context_retrieval_v2",
    "generic-retrieval-v2-dataset.v1",
    "locator-v2-pairs-relative-22222222",
    "locator-v2-reproject:",
    "locator-v2-tombstone:",
    "pre-0046 Retrieval V2 writers",
}
IMMUTABLE_COMPATIBILITY_PATTERNS = tuple(
    re.compile(rf"(?<![A-Za-z0-9_-]){re.escape(literal)}(?![A-Za-z0-9_-])")
    for literal in sorted(IMMUTABLE_COMPATIBILITY_LITERALS, key=len, reverse=True)
)
NEW_SOURCE_CLASSIFICATION = {
    CORE_FEATURE / "domain" / "locator_retrieval.py": "domain",
    CORE_FEATURE / "domain" / "locator_retrieval_filters.py": "domain_filters",
    CORE_FEATURE / "ports" / "locator_retrieval.py": "ports",
    CORE_FEATURE / "application" / "locator_retrieval.py": "application",
    REPO_ROOT
    / "packages"
    / "infinity_context_contracts"
    / "infinity_context_contracts"
    / "features"
    / "_context_building_retrieval.py": "contract",
    REPO_ROOT
    / "packages"
    / "infinity_context_contracts"
    / "infinity_context_contracts"
    / "features"
    / "_context_building_retrieval_validation.py": "contract",
    REPO_ROOT
    / "packages"
    / "infinity_context_contracts"
    / "infinity_context_contracts"
    / "features"
    / "_context_building_retrieval_filters.py": "contract_filters",
    REPO_ROOT
    / "packages"
    / "infinity_context_contracts"
    / "infinity_context_contracts"
    / "features"
    / "_context_building_retrieval_json.py": "contract_json",
    REPO_ROOT
    / "packages"
    / "infinity_context_contracts"
    / "infinity_context_contracts"
    / "features"
    / "_context_building_retrieval_capability.py": "contract_capability",
    REPO_ROOT
    / "packages"
    / "infinity_context_contracts"
    / "infinity_context_contracts"
    / "features"
    / "_context_building_retrieval_response.py": "contract_response",
    REPO_ROOT
    / "packages"
    / "infinity_context_contracts"
    / "infinity_context_contracts"
    / "features"
    / "_context_retrieval_errors.py": "contract_error",
    REPO_ROOT
    / "packages"
    / "infinity_context_contracts"
    / "infinity_context_contracts"
    / "features"
    / "_document_retrieval_projection_v1.py": "contract_projection",
    CORE_FEATURE / "domain" / "retrieval_capability.py": "domain_capability",
    CORE_FEATURE / "domain" / "retrieval_canonical.py": "domain_eval",
    CORE_FEATURE / "domain" / "retrieval_dataset.py": "domain_eval",
    CORE_FEATURE / "domain" / "retrieval_evaluation.py": "domain_eval",
    CORE_FEATURE / "domain" / "retrieval_evidence.py": "domain_eval",
    CORE_FEATURE / "domain" / "retrieval_qualification.py": "domain_eval",
    REPO_ROOT
    / "packages"
    / "infinity_context_core"
    / "infinity_context_core"
    / "features"
    / "document_ingestion"
    / "domain"
    / "retrieval_projection.py": "ingestion_domain",
    REPO_ROOT
    / "packages"
    / "infinity_context_core"
    / "infinity_context_core"
    / "features"
    / "document_ingestion"
    / "ports"
    / "projection_ownership.py": "ingestion_ports",
}
INTEGRATION_SOURCE_CLASSIFICATION = {
    SERVER_CONTEXT_BUILDING / "retrieval_service.py": "application_composition",
    SERVER_CONTEXT_BUILDING / "retrieval_mappers.py": "contract_mapping",
    SERVER_PACKAGE / "retrieval_profile_composition.py": "provider_composition",
    SERVER_PACKAGE / "retrieval_profile_outbox.py": "outbox_application_coordination",
    SERVER_PACKAGE / "api" / "v1" / "context_retrieval.py": "http_adapter",
    POSTGRES_ADAPTER / "locator_retrieval.py": "canonical_read_adapter",
    POSTGRES_ADAPTER / "projected_document_ingestion.py": "canonical_write_adapter",
    POSTGRES_ADAPTER / "locator_models.py": "canonical_schema_adapter",
    POSTGRES_ADAPTER / "retrieval_projection_mapping.py": "projection_contract_mapping",
    POSTGRES_ADAPTER
    / "migrations"
    / "0039_locator_retrieval_attributes.sql": "canonical_schema_migration",
    QDRANT_ADAPTER / "locator_profile.py": "derived_schema_adapter",
    QDRANT_ADAPTER / "locator_runtime.py": "derived_runtime_adapter",
}
STDLIB_ALLOWLIST = {
    "application": {"__future__", "asyncio", "dataclasses", "json", "math"},
    "contract": {
        "__future__",
        "collections",
        "dataclasses",
        "datetime",
        "decimal",
        "math",
        "re",
    },
    "contract_capability": {"__future__", "collections", "dataclasses", "hashlib", "json"},
    "contract_filters": {"__future__", "collections", "dataclasses"},
    "contract_json": {"__future__", "collections", "json"},
    "contract_error": {"__future__", "collections", "dataclasses"},
    "contract_projection": {"__future__", "collections", "dataclasses", "datetime", "re"},
    "contract_response": {"__future__", "collections"},
    "domain_capability": {"__future__", "dataclasses", "math"},
    "domain_eval": {
        "__future__",
        "collections",
        "dataclasses",
        "fractions",
        "hashlib",
        "json",
        "pathlib",
        "types",
        "typing",
    },
    "domain_filters": {"__future__", "dataclasses", "datetime", "math"},
    "ingestion_domain": {"__future__", "dataclasses", "datetime"},
    "ingestion_ports": {"__future__", "dataclasses", "typing"},
    "domain": {"__future__", "dataclasses", "datetime", "decimal", "math"},
    "ports": {"__future__", "typing"},
}
OWN_FEATURE_ALLOWLIST = {
    "application": {
        "infinity_context_core.features.context_building.domain.locator_retrieval",
        "infinity_context_core.features.context_building.ports.locator_retrieval",
    },
    "contract": {
        ".._json",
        "._context_building_retrieval_filters",
        "._context_building_retrieval_response",
        "._context_building_retrieval_validation",
    },
    "contract_capability": {
        ".._json",
        "._context_building_retrieval_json",
        "._context_building_retrieval_validation",
    },
    "contract_filters": {
        ".._json",
        "._context_building_retrieval_validation",
    },
    "contract_json": {"._context_building_retrieval"},
    "contract_error": {".._json"},
    "contract_projection": {".._json", "._context_building_retrieval_json"},
    "contract_response": {"._context_building_retrieval"},
    "domain_capability": set(),
    "domain_eval": {
        "infinity_context_core.features.context_building.domain.locator_retrieval",
        "infinity_context_core.features.context_building.domain.retrieval_canonical",
        "infinity_context_core.features.context_building.domain.retrieval_dataset",
        "infinity_context_core.features.context_building.domain.retrieval_evaluation",
        "infinity_context_core.features.context_building.domain.retrieval_qualification",
    },
    "domain_filters": {
        "infinity_context_core.features.context_building.domain.retrieval_capability"
    },
    "ingestion_domain": {"infinity_context_core.features.document_ingestion.domain.errors"},
    "ingestion_ports": {
        "infinity_context_core.features.document_ingestion.domain",
        "infinity_context_core.features.document_ingestion.domain.retrieval_projection",
    },
    "domain": {
        "infinity_context_core.features.context_building.domain.locator_retrieval_filters",
        "infinity_context_core.features.context_building.domain.retrieval_capability",
    },
    "ports": {"infinity_context_core.features.context_building.domain.locator_retrieval"},
}


def test_every_locator_retrieval_source_has_fail_closed_dependency_classification() -> None:
    assert all(path.is_file() for path in NEW_SOURCE_CLASSIFICATION)
    assert set(NEW_SOURCE_CLASSIFICATION.values()) == set(STDLIB_ALLOWLIST)
    assert all(path.is_file() for path in INTEGRATION_SOURCE_CLASSIFICATION)
    assert len(set(INTEGRATION_SOURCE_CLASSIFICATION.values())) == len(
        INTEGRATION_SOURCE_CLASSIFICATION
    )


def test_locator_retrieval_imports_follow_explicit_layer_allowlists() -> None:
    violations: list[str] = []
    for path, classification in NEW_SOURCE_CLASSIFICATION.items():
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for name in _imports(tree):
            root = name.lstrip(".").split(".", 1)[0]
            if (
                root not in STDLIB_ALLOWLIST[classification]
                and name not in OWN_FEATURE_ALLOWLIST[classification]
            ):
                violations.append(f"{classification}:{path.name}:{name}")
    assert violations == []


def test_locator_retrieval_layer_dependency_direction_is_inward_only() -> None:
    dependencies = {
        classification: {
            name
            for name in _imports(ast.parse(path.read_text(encoding="utf-8"), filename=str(path)))
            if name.startswith("infinity_context_core.features.context_building")
        }
        for path, classification in NEW_SOURCE_CLASSIFICATION.items()
        if classification in {"application", "contract", "domain", "ports"}
    }
    assert dependencies["domain"] == {
        "infinity_context_core.features.context_building.domain.locator_retrieval_filters",
        "infinity_context_core.features.context_building.domain.retrieval_capability",
    }
    assert dependencies["ports"] == {
        "infinity_context_core.features.context_building.domain.locator_retrieval"
    }
    assert dependencies["application"] == {
        "infinity_context_core.features.context_building.domain.locator_retrieval",
        "infinity_context_core.features.context_building.ports.locator_retrieval",
    }
    assert dependencies["contract"] == set()


def test_locator_retrieval_boundary_adr_is_accepted_and_locator_only() -> None:
    adr = (REPO_ROOT / "docs" / "adr" / "ADR-0011-locator-retrieval-boundary.md").read_text(
        encoding="utf-8"
    )
    assert "Status: accepted" in adr
    assert "locator-only" in adr
    assert "weighted_rrf_canonical_preferences.v1" in adr
    assert "document-retrieval-projection.v1" in adr
    assert "Meeting" not in adr
    assert "Discord" not in adr


def test_current_retrieval_has_no_v2_or_old_serving_identifiers() -> None:
    """Keep V2 at explicit immutable boundaries, never in current names or strings."""

    assert "vendor" not in EXPLICIT_NON_SOURCE_DIRECTORY_NAMES
    violations: list[str] = []
    for path in _current_text_files():
        relative = path.relative_to(REPO_ROOT)
        text = path.read_text(encoding="utf-8")
        violations.extend(_source_boundary_violations(relative, text))
    assert violations == []
    assert not (SERVER_PACKAGE / "serving_identity.py").exists()
    assert not (SERVER_PACKAGE / "retrieval_composition.py").exists()
    assert not (POSTGRES_ADAPTER / "locator_projection_maintenance.py").exists()


def test_retrieval_boundary_guard_catches_python_and_typescript_mutations() -> None:
    mutations = {
        Path("packages/example/python_named_split.py"): (
            "import importlib\n"
            "old = importlib.import_module('infinity_context_adapters.postgres.' + "
            "'locator_' + 'projection_maintenance')\n"
            "legacy = getattr(object(), 'locator_' + 'vector_index')\n"
            "prefix = 'locator_'\nversion = 'v2'\nlabel = prefix + version\n"
        ),
        Path("packages/example/typescript_named_split.ts"): (
            "const old = container['locator_' + 'vector_index'];\n"
            "const module = import('infinity_context_server.' + 'retrieval_composition');\n"
            "const prefix = 'locator_';\nconst version = 'v2';\n"
            "const label = prefix + version;\n"
        ),
        Path("packages/example/typescript_template_split.ts"): (
            "const prefix = 'retrieval-';\nconst version = 'v2';\n"
            "const profile = `${prefix}${version}`;\n"
        ),
        Path("packages/example/generic_runtime.py"): "name = 'locator_v2_runtime'\n",
        Path("packages/example/laundered_marker.py"): (
            "name = 'locator-v2-pairs-relative-22222222-extra'\n"
        ),
        Path("tests/e2e/mutable_name.py"): "collection = 'locator-v2-e2e-live'\n",
        Path("packages/example/production_profile.py"): (
            "profile_id = 'locator-v2-production-default'\n"
        ),
    }
    for relative, text in mutations.items():
        assert _source_boundary_violations(relative, text), relative


def test_retrieval_boundary_guard_allows_exact_frozen_fixture_identifier() -> None:
    samples = {
        Path(
            "packages/infinity_context_contracts/infinity_context_contracts/fixtures/"
            "context_retrieval_v2/frozen.py"
        ): ("context_retrieval_v2 = 'fixtures/context_retrieval_v2/request.json'\n"),
        Path("packages/infinity_context_ts_sdk/fixtures/context_retrieval_v2/frozen.ts"): (
            "const context_retrieval_v2 = 'fixtures/context_retrieval_v2/request.json';\n"
        ),
    }
    for relative, text in samples.items():
        assert _source_boundary_violations(relative, text) == [], relative


@pytest.mark.parametrize(
    "name",
    ["hostile.whl", "hostile.zip", "hostile.tar", "hostile.tar.gz", "hostile.tgz"],
)
def test_retrieval_archive_guard_fails_closed_on_malformed_supported_archives(
    tmp_path: Path, name: str
) -> None:
    archive = tmp_path / name
    archive.write_bytes(b"not a supported archive")
    with pytest.raises(ArchiveSourceGuardError, match="unreadable or malformed"):
        inspect_source_archive(archive, text_suffixes=TEXT_SUFFIXES)


def test_retrieval_archive_guard_fails_closed_on_unreadable_wheel(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    archive = tmp_path / "supported.whl"
    with zipfile.ZipFile(archive, "w") as wheel:
        wheel.writestr("packages/example/source.py", "safe = True\n")

    def unreadable(*_args: object, **_kwargs: object) -> object:
        raise OSError("hostile unreadable mutation")

    monkeypatch.setattr(archive_guard.zipfile, "ZipFile", unreadable)
    with pytest.raises(ArchiveSourceGuardError, match="unreadable or malformed"):
        inspect_source_archive(archive, text_suffixes=TEXT_SUFFIXES)


def test_retrieval_archive_guard_detects_hostile_wheel_source(tmp_path: Path) -> None:
    archive = tmp_path / "hostile.whl"
    member = Path("packages/example/hostile.py")
    with zipfile.ZipFile(archive, "w") as wheel:
        wheel.writestr(member.as_posix(), "runtime = 'locator_v2_runtime'\n")
    inventory = inspect_source_archive(archive, text_suffixes=TEXT_SUFFIXES)
    assert _source_boundary_violations(member, inventory.text_members[0][1])


def test_retrieval_archive_guard_enforces_member_name_and_byte_bounds(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    traversal = tmp_path / "traversal.whl"
    with zipfile.ZipFile(traversal, "w") as wheel:
        wheel.writestr("../packages/example/source.py", "safe = True\n")
    with pytest.raises(ArchiveSourceGuardError, match="unsafe archive member name"):
        inspect_source_archive(traversal, text_suffixes=TEXT_SUFFIXES)

    oversized = tmp_path / "oversized.whl"
    with zipfile.ZipFile(oversized, "w") as wheel:
        wheel.writestr("packages/example/source.py", "safe = True\n")
    monkeypatch.setattr(archive_guard, "MAX_ARCHIVE_MEMBER_BYTES", 8)
    with pytest.raises(ArchiveSourceGuardError, match="member byte limit"):
        inspect_source_archive(oversized, text_suffixes=TEXT_SUFFIXES)


def test_retrieval_archive_guard_enforces_archive_entry_and_total_bounds(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    archive = tmp_path / "bounded.tar.gz"
    with tarfile.open(archive, "w:gz") as bundle:
        for name in ("one.py", "two.py"):
            payload = b"safe = True\n"
            member = tarfile.TarInfo(name)
            member.size = len(payload)
            bundle.addfile(member, io.BytesIO(payload))

    monkeypatch.setattr(archive_guard, "MAX_ARCHIVE_BYTES", 8)
    with pytest.raises(ArchiveSourceGuardError, match="archive byte limit"):
        inspect_source_archive(archive, text_suffixes=TEXT_SUFFIXES)

    monkeypatch.setattr(archive_guard, "MAX_ARCHIVE_BYTES", 100 * 1024 * 1024)
    monkeypatch.setattr(archive_guard, "MAX_ARCHIVE_ENTRIES", 1)
    with pytest.raises(ArchiveSourceGuardError, match="entry limit"):
        inspect_source_archive(archive, text_suffixes=TEXT_SUFFIXES)

    monkeypatch.setattr(archive_guard, "MAX_ARCHIVE_ENTRIES", 4_096)
    monkeypatch.setattr(archive_guard, "MAX_ARCHIVE_TEXT_BYTES", 8)
    with pytest.raises(ArchiveSourceGuardError, match="text byte limit"):
        inspect_source_archive(archive, text_suffixes=TEXT_SUFFIXES)


def test_retrieval_archive_guard_rejects_tar_links_and_special_members(tmp_path: Path) -> None:
    for kind, configure in (
        ("link", lambda member: setattr(member, "type", tarfile.SYMTYPE)),
        ("fifo", lambda member: setattr(member, "type", tarfile.FIFOTYPE)),
    ):
        archive = tmp_path / f"{kind}.tar"
        with tarfile.open(archive, "w") as bundle:
            member = tarfile.TarInfo("packages/example/source.py")
            configure(member)
            bundle.addfile(member)
        with pytest.raises(ArchiveSourceGuardError, match="archive member"):
            inspect_source_archive(archive, text_suffixes=TEXT_SUFFIXES)


def test_all_chunk_delete_aggregate_families_are_version_fenced() -> None:
    class Vector:
        def __init__(self) -> None:
            self.points = {"chunk-a": 5}
            self.deleted: list[tuple[tuple[str, ...], int]] = []

        async def delete_chunks_if_version(
            self, chunk_ids: tuple[str, ...], *, canonical_version: int
        ) -> VectorWriteResult:
            self.deleted.append((chunk_ids, canonical_version))
            for chunk_id in chunk_ids:
                if self.points.get(chunk_id) == canonical_version:
                    del self.points[chunk_id]
            return VectorWriteResult.ok(len(chunk_ids))

    class Poison:
        def __getattr__(self, name: str) -> object:
            raise AssertionError(f"drained projection lane accessed: {name}")

    vector = Vector()
    container = SimpleNamespace(vector_index=vector)
    for name in REMOVED_PROJECTION_NAMES:
        setattr(container, name, Poison())
    process = ProjectionOutboxProcess(container)
    for aggregate_type in ("locator_chunk", "document", "thread"):
        for version in (4, 5):
            vector.points["chunk-a"] = 5
            payload: dict[str, object] = {"chunk_ids": ["chunk-a"]}
            aggregate_version = version if aggregate_type == "locator_chunk" else None
            if aggregate_type != "locator_chunk":
                payload["chunk_versions"] = [{"chunk_id": "chunk-a", "canonical_version": version}]
            asyncio.run(
                process.handle_vector_delete_chunks(
                    ClaimedOutboxJob(
                        id=len(vector.deleted) + 1,
                        event_type="vector.delete_chunks",
                        aggregate_id="aggregate-a",
                        aggregate_version=aggregate_version,
                        attempt_count=0,
                        workload_class="projection",
                        fairness_key=f"{aggregate_type}:aggregate-a",
                        payload_json=payload,
                        aggregate_type=aggregate_type,
                    )
                )
            )
            assert ("chunk-a" in vector.points) is (version == 4), aggregate_type

    assert vector.deleted == [(("chunk-a",), version) for _family in range(3) for version in (4, 5)]
    assert REMOVED_PROJECTION_NAMES.isdisjoint(Container.__annotations__)


def test_unversioned_document_and_thread_deletes_fail_closed() -> None:
    process = ProjectionOutboxProcess(SimpleNamespace(vector_index=object()))
    for aggregate_type in ("document", "thread"):
        job = ClaimedOutboxJob(
            id=1,
            event_type="vector.delete_chunks",
            aggregate_id="aggregate-a",
            aggregate_version=None,
            attempt_count=0,
            workload_class="projection",
            fairness_key=f"{aggregate_type}:aggregate-a",
            payload_json={"chunk_ids": ["chunk-a"]},
            aggregate_type=aggregate_type,
        )
        with pytest.raises(
            OutboxProjectionError,
            match="vector.delete_chunks",
        ) as raised:
            asyncio.run(process.handle_vector_delete_chunks(job))
        assert raised.value.diagnostic_code == "vector.delete_canonical_versions_rebuild_required"


def test_drained_retrieval_runtime_has_no_dynamic_or_packaged_consumer() -> None:
    profile_source = (SERVER_PACKAGE / "retrieval_profile_composition.py").read_text(
        encoding="utf-8"
    )
    composition_source = (SERVER_PACKAGE / "composition.py").read_text(encoding="utf-8")
    assert "fallback" not in profile_source
    assert "build_locator_retrieval_service" not in composition_source
    assert importlib.util.find_spec(OLD_SERVING_MODULE) is None
    assert importlib.util.find_spec(REMOVED_RETRIEVAL_MODULE) is None
    assert importlib.util.find_spec(REMOVED_PROJECTION_MODULE) is None

    removed_members = {
        "infinity_context_server/serving_identity.py",
        "infinity_context_server/retrieval_composition.py",
        "infinity_context_adapters/postgres/locator_projection_maintenance.py",
    }
    violations: list[str] = []
    for path in _current_text_files():
        text = path.read_text(encoding="utf-8")
        if not _immutable_v2_path(path.relative_to(REPO_ROOT)) and any(
            module in text
            for module in (
                OLD_SERVING_MODULE,
                REMOVED_RETRIEVAL_MODULE,
                REMOVED_PROJECTION_MODULE,
            )
        ):
            violations.append(f"{path.relative_to(REPO_ROOT)}:removed module consumer")
    archive_paths = {
        path
        for pattern in ("*.tar", "*.tar.gz", "*.tgz", "*.whl", "*.zip")
        for path in REPO_ROOT.rglob(pattern)
        if not _in_explicit_non_source_directory(path)
    }
    for path in sorted(archive_paths):
        try:
            inventory = inspect_source_archive(path, text_suffixes=TEXT_SUFFIXES)
        except ArchiveSourceGuardError as error:
            violations.append(f"{path.relative_to(REPO_ROOT)}:{error}")
            continue
        violations.extend(
            f"{path.relative_to(REPO_ROOT)}:{name}"
            for name in inventory.member_names
            if any(name.endswith(member) for member in removed_members)
        )
        for member, source in inventory.text_members:
            violations.extend(
                f"{path.relative_to(REPO_ROOT)}:{violation}"
                for violation in _source_boundary_violations(
                    _archive_member_relative(member), source
                )
            )
            if member.name == "retrieval_profile_composition.py" and "fallback" in source:
                violations.append(f"{path.relative_to(REPO_ROOT)}:{member}:drained fallback")
    assert violations == []


def test_retrieval_runtime_lifecycle_uses_explicit_capabilities() -> None:
    dynamic_lifecycle_probe = re.compile(
        r"getattr\([^)]*,\s*['\"](?:start_runtime|close_runtime|reconcile_active)['\"]"
    )
    violations = [
        str(path.relative_to(REPO_ROOT))
        for path in (REPO_ROOT / "packages").rglob("*.py")
        if dynamic_lifecycle_probe.search(path.read_text(encoding="utf-8"))
    ]
    assert violations == []


def test_versioned_retrieval_filenames_are_explicit_immutable_boundaries() -> None:
    versioned_paths = {
        path
        for package_root in PRODUCTION_PACKAGE_ROOTS
        for path in package_root.rglob("*")
        if path.is_file()
        and ("retrieval_v2" in path.name or "retrieval-v2" in path.name)
        and "fixtures/context_retrieval_v2" not in path.as_posix()
        and "/migrations/" not in path.as_posix()
    }
    assert versioned_paths == VERSIONED_RETRIEVAL_PATH_ALLOWLIST


def _imports(tree: ast.AST) -> tuple[str, ...]:
    imported: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.append(f"{'.' * node.level}{node.module}")
    return tuple(imported)


def _defined_or_referenced_names(node: ast.AST) -> tuple[str, ...]:
    if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
        return (node.name,)
    if isinstance(node, ast.Name):
        return (node.id,)
    if isinstance(node, ast.Attribute):
        return (node.attr,)
    if isinstance(node, ast.alias):
        return (node.name, node.asname or "")
    return ()


def _source_boundary_violations(relative: Path, text: str) -> list[str]:
    violations: list[str] = []
    lines = text.splitlines()
    removed_modules = {
        OLD_SERVING_MODULE,
        REMOVED_RETRIEVAL_MODULE,
        REMOVED_PROJECTION_MODULE,
    }
    if "serving_identity" in relative.name:
        violations.append(f"{relative}:old serving filename")
    if (
        "retrieval_v2" in relative.name or "retrieval-v2" in relative.name
    ) and not _immutable_v2_path(relative):
        violations.append(f"{relative}:current V2 filename")
    for line_number, line in enumerate(lines, 1):
        if "serving_identity" in line:
            violations.append(f"{relative}:{line_number}:old serving name")
        if any(name in line for name in REMOVED_PROJECTION_NAMES) and not _immutable_v2_path(
            relative
        ):
            violations.append(f"{relative}:{line_number}:removed projection name")
        if _contains_current_v2_name(line) and not _immutable_v2_path(relative):
            violations.append(f"{relative}:{line_number}:current V2 name")
    if relative.suffix in {".py", ".pyi"}:
        tree = ast.parse(text, filename=str(relative))
        static_environment = _python_static_environment(tree)
        violations.extend(
            f"{relative}:{name}"
            for name in _imports(tree)
            if name.lstrip(".") in removed_modules
            or name.lstrip(".").endswith(
                (
                    ".serving_identity",
                    ".retrieval_composition",
                    ".locator_projection_maintenance",
                )
            )
        )
        for node in ast.walk(tree):
            for name in _defined_or_referenced_names(node):
                if (
                    _old_retrieval_identifier(name) or _contains_current_v2_name(name)
                ) and not _immutable_v2_path(relative):
                    violations.append(f"{relative}:{name}")
            value = _static_python_string(node, static_environment)
            if value is not None:
                if any(module in value for module in removed_modules) and not _immutable_v2_path(
                    relative
                ):
                    violations.append(f"{relative}:dynamic old module string")
                if any(name in value for name in REMOVED_PROJECTION_NAMES) and not (
                    _immutable_v2_path(relative)
                ):
                    violations.append(f"{relative}:dynamic removed projection name")
                if _contains_current_v2_name(value) and not _immutable_v2_path(relative):
                    violations.append(f"{relative}:dynamic current V2 name")
    elif relative.suffix in {".cts", ".mts", ".ts", ".tsx"} or relative.name.endswith(
        (".d.cts", ".d.ts")
    ):
        for line_number, line in enumerate(lines, 1):
            violations.extend(
                f"{relative}:{line_number}:{name}"
                for name in re.findall(r"[A-Za-z_$][A-Za-z0-9_$]*", line)
                if (_old_retrieval_identifier(name) or _contains_current_v2_name(name))
                and not _immutable_v2_path(relative)
            )
        for value in _typescript_static_strings(text):
            line_number = text[: text.find(value)].count("\n") + 1 if value in text else 1
            if any(module in value for module in removed_modules) and not _immutable_v2_path(
                relative
            ):
                violations.append(f"{relative}:{line_number}:dynamic old module string")
            if any(name in value for name in REMOVED_PROJECTION_NAMES) and not (
                _immutable_v2_path(relative)
            ):
                violations.append(f"{relative}:{line_number}:dynamic removed projection name")
            if _contains_current_v2_name(value) and not _immutable_v2_path(relative):
                violations.append(f"{relative}:{line_number}:dynamic current V2 name")
    return violations


def _static_python_string(node: ast.AST, environment: dict[str, str]) -> str | None:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.Name):
        return environment.get(node.id)
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        left = _static_python_string(node.left, environment)
        right = _static_python_string(node.right, environment)
        return None if left is None or right is None else left + right
    if isinstance(node, ast.JoinedStr):
        parts: list[str] = []
        for value in node.values:
            if isinstance(value, ast.FormattedValue):
                part = _static_python_string(value.value, environment)
            else:
                part = _static_python_string(value, environment)
            if part is None:
                return None
            parts.append(part)
        return "".join(parts)
    return None


def _python_static_environment(tree: ast.AST) -> dict[str, str]:
    assignments: list[tuple[str, ast.AST]] = []
    for node in ast.walk(tree):
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else (node.target,)
            if node.value is not None:
                assignments.extend(
                    (target.id, node.value) for target in targets if isinstance(target, ast.Name)
                )
    assignment_counts: dict[str, int] = {}
    for name, _expression in assignments:
        assignment_counts[name] = assignment_counts.get(name, 0) + 1
    assignments = [item for item in assignments if assignment_counts[item[0]] == 1]
    environment: dict[str, str] = {}
    for _ in range(len(assignments) + 1):
        changed = False
        for name, expression in assignments:
            value = _static_python_string(expression, environment)
            if value is not None and environment.get(name) != value:
                environment[name] = value
                changed = True
        if not changed:
            break
    return environment


def _typescript_static_strings(source: str) -> tuple[str, ...]:
    assignment_pattern = re.compile(
        r"^\s*(?:const|let|var)\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*=\s*(.*?)\s*;?\s*$",
        re.MULTILINE,
    )
    discovered_assignments = tuple(assignment_pattern.findall(source))
    assignment_counts: dict[str, int] = {}
    for name, _expression in discovered_assignments:
        assignment_counts[name] = assignment_counts.get(name, 0) + 1
    assignments = tuple(item for item in discovered_assignments if assignment_counts[item[0]] == 1)
    environment: dict[str, str] = {}
    for _ in range(len(assignments) + 1):
        changed = False
        for name, expression in assignments:
            value = _typescript_static_expression(expression, environment)
            if value is not None and environment.get(name) != value:
                environment[name] = value
                changed = True
        if not changed:
            break
    values = set(environment.values())
    for match in re.finditer(r"`(?:[^`\\]|\\.)*`", source):
        value = _typescript_static_expression(match.group(0), environment)
        if value is not None:
            values.add(value)
    return tuple(sorted(values))


def _typescript_static_expression(expression: str, environment: dict[str, str]) -> str | None:
    expression = expression.strip().removesuffix(";").strip()
    parts = _split_typescript_addition(expression)
    if len(parts) > 1:
        values = tuple(_typescript_static_expression(part, environment) for part in parts)
        return None if any(value is None for value in values) else "".join(values)  # type: ignore[arg-type]
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", expression):
        return environment.get(expression)
    if len(expression) >= 2 and expression[0] == expression[-1] and expression[0] in "'\"":
        return bytes(expression[1:-1], "utf-8").decode("unicode_escape")
    if len(expression) >= 2 and expression[0] == expression[-1] == "`":
        body = expression[1:-1]
        cursor = 0
        values: list[str] = []
        for match in re.finditer(r"\$\{\s*([A-Za-z_$][A-Za-z0-9_$]*)\s*\}", body):
            values.append(body[cursor : match.start()])
            resolved = environment.get(match.group(1))
            if resolved is None:
                return None
            values.append(resolved)
            cursor = match.end()
        values.append(body[cursor:])
        return "".join(values)
    return None


def _split_typescript_addition(expression: str) -> tuple[str, ...]:
    parts: list[str] = []
    start = 0
    quote: str | None = None
    escaped = False
    for index, character in enumerate(expression):
        if escaped:
            escaped = False
            continue
        if character == "\\":
            escaped = True
            continue
        if quote is not None:
            if character == quote:
                quote = None
            continue
        if character in "'\"`":
            quote = character
        elif character == "+":
            parts.append(expression[start:index])
            start = index + 1
    parts.append(expression[start:])
    return tuple(part.strip() for part in parts)


def _current_text_files() -> tuple[Path, ...]:
    guard = Path(__file__).resolve()
    paths: set[Path] = set()
    for root in CURRENT_SOURCE_ROOTS:
        for directory, names, filenames in os.walk(root):
            relative_directory = Path(directory).relative_to(REPO_ROOT)
            names[:] = [
                name
                for name in names
                if relative_directory / name not in EXPLICIT_NON_SOURCE_DIRECTORIES
                and name not in EXPLICIT_NON_SOURCE_DIRECTORY_NAMES
            ]
            for filename in filenames:
                path = Path(directory) / filename
                if path != guard and (
                    path.suffix in TEXT_SUFFIXES or path.name.endswith((".d.cts", ".d.ts"))
                ):
                    paths.add(path)
    paths.update(
        path for path in (REPO_ROOT / "README.md", REPO_ROOT / "pyproject.toml") if path.exists()
    )
    return tuple(sorted(paths))


def _in_explicit_non_source_directory(path: Path) -> bool:
    relative = path.relative_to(REPO_ROOT)
    return any(
        prefix == parent or prefix in parent.parents
        for parent in relative.parents
        for prefix in EXPLICIT_NON_SOURCE_DIRECTORIES
    ) or any(name in EXPLICIT_NON_SOURCE_DIRECTORY_NAMES for name in relative.parts)


def _archive_member_relative(path: Path) -> Path:
    for root_name in ("packages", "docs", "examples", "scripts", "tests", "plugins", ".github"):
        if root_name in path.parts:
            return Path(*path.parts[path.parts.index(root_name) :])
    return path


def _immutable_v2_path(relative: Path) -> bool:
    return relative in IMMUTABLE_V2_PATHS or any(
        relative == prefix or prefix in relative.parents for prefix in IMMUTABLE_WIRE_PATH_PREFIXES
    )


def _contains_current_v2_name(value: str) -> bool:
    if "v2" not in value.lower():
        return False
    sanitized = value
    for pattern in IMMUTABLE_COMPATIBILITY_PATTERNS:
        sanitized = pattern.sub("", sanitized)
    return CURRENT_V2_NAME.search(sanitized) is not None


def _old_retrieval_identifier(value: str) -> bool:
    return (
        value not in IMMUTABLE_COMPATIBILITY_LITERALS
        and OLD_RETRIEVAL_IDENTIFIER.search(value) is not None
    )
