"""Static relation query vocabularies for memory-comparison rerank planning."""

from __future__ import annotations

RELATION_QUERY_VARIANTS = {
    "action": (
        "book",
        "booked",
        "bring",
        "brought",
        "complete",
        "completed",
        "create",
        "created",
        "draw",
        "drew",
        "fix",
        "fixed",
        "made",
        "make",
        "paint",
        "painted",
        "prepare",
        "prepared",
        "repair",
        "repaired",
        "schedule",
        "scheduled",
        "send",
        "sent",
        "share",
        "shared",
        "take",
        "took",
    ),
    "activity": (
        "activities",
        "hobby",
        "hobbies",
        "partake",
        "do",
        "class",
        "kids",
        "photo",
        "image",
        "family",
        "weekend",
        "unplug",
    ),
    "age": ("old", "years", "year", "birthday", "born"),
    "anniversary": ("date", "month", "year", "wedding", "married"),
    "advise": ("advised", "recommend", "recommended", "suggest", "suggested"),
    "ask": ("asked", "request", "requested", "told"),
    "attend": (
        "attended",
        "attending",
        "event",
        "conference",
        "meeting",
        "class",
        "workshop",
    ),
    "birthday": ("birthday", "born", "age", "years", "ago"),
    "book": (
        "books",
        "reading",
        "read",
        "bookshelf",
        "kids",
        "stories",
    ),
    "bookshelf": (
        "books",
        "book",
        "reading",
        "read",
        "kids",
        "stories",
    ),
    "brother": ("sibling", "sister", "family"),
    "bought": ("buy", "purchased", "got"),
    "bring": ("brought", "take", "took"),
    "brought": ("bring", "brought", "took"),
    "call": ("called", "conversation", "talked"),
    "camp": (
        "camped",
        "camping",
        "family",
        "unplug",
        "connection",
        "close",
        "together",
        "outdoors",
        "trip",
        "tent",
        "site",
    ),
    "career": ("path", "field", "job", "work", "working", "profession", "option"),
    "cause": ("caused", "because", "reason"),
    "choose": ("chose", "picked", "selected"),
    "consider": ("considered", "considering", "looked at", "thinking"),
    "conference": ("event", "attend", "going"),
    "contact": (
        "address",
        "cell",
        "contact",
        "e-mail",
        "email",
        "mobile",
        "number",
        "phone",
        "telephone",
    ),
    "deadline": ("due", "date", "finish", "complete", "task"),
    "decide": ("decided", "chose", "planned", "thinking", "figuring"),
    "dating": ("partner", "relationship", "boyfriend", "girlfriend"),
    "destress": (
        "stress",
        "relax",
        "unwind",
        "clear mind",
        "therapy",
        "class",
        "running",
        "activity",
        "practice",
        "routine",
        "therapeutic",
        "creative",
        "express",
        "decompress",
        "self-care",
    ),
    "diet": (
        "avoid",
        "dairy",
        "dietary",
        "eat",
        "food",
        "gluten",
        "meat",
        "pork",
        "restriction",
        "vegan",
        "vegetarian",
    ),
    "discus": ("discuss", "discussed", "discussion", "talk", "conversation"),
    "discuss": ("discussed", "discussion", "talk", "talked", "conversation"),
    "talk": ("talked", "discuss", "discussed", "conversation", "chat"),
    "chat": ("chatted", "talk", "talked", "conversation", "message"),
    "class": ("course", "lesson", "take", "taking", "study"),
    "education": (
        "school",
        "college",
        "university",
        "study",
        "studying",
        "studies",
        "major",
        "majoring",
        "degree",
        "campus",
    ),
    "employment": (
        "job",
        "company",
        "employer",
        "work",
        "worked",
        "working",
        "workplace",
        "occupation",
        "profession",
        "role",
        "office",
        "career",
    ),
    "enjoy": ("enjoyed", "like", "liked", "love", "fan", "interested"),
    "enroll": (
        "enrolled",
        "enrolling",
        "registered",
        "registration",
        "signup",
        "class",
        "course",
        "lesson",
    ),
    "engag": ("engaged", "fiance", "fiancee", "partner", "wedding"),
    "excite": ("excited", "looking forward", "enthusiastic", "thrilled"),
    "favorite": (
        "favourite",
        "prefer",
        "like",
        "love",
        "color",
        "food",
        "restaurant",
        "music",
        "song",
        "book",
    ),
    "favourite": (
        "favorite",
        "prefer",
        "like",
        "love",
        "color",
        "food",
        "restaurant",
        "music",
        "song",
        "book",
    ),
    "feel": (
        "felt",
        "feeling",
        "reaction",
        "response",
        "nervous",
        "relieved",
        "proud",
        "worried",
        "upset",
    ),
    "field": ("career", "option", "education", "study", "work", "working", "profession"),
    "exercise": ("workout", "running", "yoga", "sport", "activity"),
    "child": ("children", "kid", "kids", "son", "daughter", "parent", "family"),
    "children": ("child", "kid", "kids", "son", "daughter", "parent", "family"),
    "daughter": ("child", "kid", "family", "parent", "mother", "father"),
    "family": ("parent", "mother", "father", "child", "children", "partner", "spouse"),
    "father": ("dad", "parent", "family", "mother", "child", "children"),
    "boyfriend": ("partner", "dating", "relationship"),
    "boss": ("manager", "work", "team", "colleague"),
    "colleague": ("coworker", "work", "team", "teammate"),
    "coworker": ("colleague", "work", "team", "teammate"),
    "get": ("got", "receive", "received"),
    "got": ("get", "receive", "received"),
    "gift": ("gift", "gave", "received", "special"),
    "girlfriend": ("partner", "dating", "relationship"),
    "give": ("gave", "giving", "offered"),
    "go": ("went", "going", "visited"),
    "current": ("known", "years", "been", "existing", "ongoing"),
    "compare": ("comparison", "difference", "different", "alternative", "instead"),
    "friend": ("friends", "group", "family", "mentors", "support"),
    "different": ("difference", "alternative", "compare", "instead"),
    "difference": ("different", "alternative", "compare", "instead"),
    "former": ("formerly", "previously", "earlier", "before", "used to"),
    "grow": ("growing", "grew", "childhood", "journey", "upbringing"),
    "group": ("friends", "family", "mentors", "support"),
    "health": (
        "doctor",
        "therapist",
        "medication",
        "medicine",
        "prescription",
        "allergy",
        "allergic",
        "condition",
        "health",
        "clinic",
        "appointment",
        "take",
        "taking",
    ),
    "hobby": (
        "hobbies",
        "pastime",
        "leisure",
        "fun",
        "activity",
        "activities",
        "painting",
        "paint",
        "running",
        "run",
        "hiking",
        "hike",
        "yoga",
        "tennis",
    ),
    "help": ("helped", "helping", "assist", "support"),
    "hike": (
        "hiking",
        "hiked",
        "trail",
        "waterfall",
        "outdoors",
        "went",
        "spot",
        "weekend",
        "summer",
        "photo",
        "pic",
    ),
    "husband": ("spouse", "partner", "married", "marriage", "wife", "family"),
    "fiance": ("fiancee", "engaged", "partner", "wedding"),
    "fiancee": ("fiance", "engaged", "partner", "wedding"),
    "manager": ("boss", "work", "team", "colleague"),
    "mentor": ("mentors", "support", "guide", "advisor"),
    "message": ("messaged", "send", "sent", "text"),
    "messag": ("message", "messaged", "send", "sent", "text"),
    "neighbor": ("neighbour", "nearby", "home", "building"),
    "identity": (
        "pride",
        "gender",
        "story",
        "identify",
        "self",
        "person",
        "background",
        "community",
        "support",
        "inspiring",
        "accepted",
        "courage",
        "embrace",
    ),
    "interest": ("interested", "prefer", "enjoy", "like", "outdoors", "park"),
    "join": ("joined", "joining", "group", "community", "class", "club", "event"),
    "learn": ("learned", "learning", "studied"),
    "like": ("liked", "enjoy", "enjoyed", "love"),
    "live": ("lived", "living", "home", "city", "place"),
    "love": ("loved", "enjoy", "enjoyed", "like"),
    "make": ("made", "create", "created"),
    "marry": (
        "married",
        "marriage",
        "wedding",
        "years",
        "anniversary",
        "husband",
        "wife",
        "spouse",
        "bride",
        "dress",
    ),
    "meet": ("met", "meeting", "friends", "family", "mentors", "gathering"),
    "mention": ("mentioned", "said", "talked", "told"),
    "nickname": ("alias", "call", "called", "calls", "name", "named"),
    "mother": ("mom", "parent", "family", "father", "child", "children"),
    "move": ("moved", "from", "relocated", "came", "home", "country", "origin"),
    "offer": ("offered", "give", "gave"),
    "origin": (
        "from",
        "home",
        "city",
        "country",
        "grew up",
        "born",
        "hometown",
        "childhood",
        "raised",
        "originally",
    ),
    "relocate": ("relocated", "from", "moved", "home", "country", "origin"),
    "relocated": ("relocated", "from", "moved", "home", "country", "origin"),
    "relocation": ("relocated", "from", "moved", "home", "country", "origin"),
    "plan": (
        "planned",
        "planning",
        "going to",
        "want",
        "dream",
        "family",
        "loving home",
        "kids",
    ),
    "political": (
        "politics",
        "leaning",
        "belief",
        "views",
        "values",
        "rights",
        "lgbtq",
        "social",
        "activism",
        "policy",
        "support",
        "accept",
    ),
    "parent": ("mother", "father", "mom", "dad", "family", "child", "children"),
    "partner": ("spouse", "husband", "wife", "relationship", "dating", "family"),
    "pet": (
        "dog",
        "cat",
        "animal",
        "breed",
        "named",
        "name",
        "puppy",
        "kitten",
        "retriever",
        "labrador",
    ),
    "participate": (
        "participated",
        "participating",
        "participation",
        "event",
        "group",
        "class",
        "workshop",
        "activity",
    ),
    "path": ("career", "field", "work", "working", "profession", "direction"),
    "previous": ("previously", "earlier", "before", "used to", "former"),
    "promise": ("promised", "commit", "committed", "said", "will"),
    "prioritize": (
        "prioritized",
        "self-care",
        "routine",
        "refresh",
        "present",
        "wellness",
        "balance",
    ),
    "pursue": (
        "pursued",
        "pursuing",
        "career",
        "education",
        "study",
        "field",
        "support",
        "similar",
        "issues",
        "keen",
    ),
    "raise": ("raised", "raising", "awareness", "fundraiser"),
    "purchas": ("purchased", "buy", "bought", "got"),
    "purchase": ("purchased", "buy", "bought", "got"),
    "receive": ("received", "got", "support", "help", "growing up"),
    "recommend": ("recommended", "suggested", "advised", "told"),
    "request": ("requested", "ask", "asked", "message"),
    "say": ("said", "tell", "told", "mention", "mentioned"),
    "said": ("say", "tell", "told", "mention", "mentioned"),
    "send": ("sent", "message", "messaged", "text"),
    "sent": ("send", "message", "messaged", "text"),
    "register": (
        "registered",
        "registration",
        "signup",
        "signed up",
        "class",
        "course",
        "lesson",
    ),
    "read": ("reading", "books", "book", "bookshelf"),
    "religious": (
        "religion",
        "faith",
        "church",
        "belief",
        "spiritual",
        "journey",
        "change",
        "changing",
        "growth",
        "acceptance",
    ),
    "relationship": (
        "status",
        "parent",
        "breakup",
        "family",
        "kids",
        "friend",
        "support",
        "challenge",
        "dating",
        "partner",
        "married",
        "boyfriend",
        "girlfriend",
        "fiance",
        "fiancee",
        "engaged",
    ),
    "roommate": ("housemate", "apartment", "home", "living", "neighbor"),
    "realize": ("realized", "learned", "understood"),
    "remember": ("reminder", "remembered", "bring", "take", "need"),
    "research": ("researching", "looked into", "looking into", "check out", "checked out"),
    "run": ("ran", "running", "race", "charity"),
    "sign": ("signed", "signup", "class", "registered"),
    "skill": (
        "language",
        "speak",
        "speaks",
        "spoken",
        "bilingual",
        "know",
        "fluent",
        "instrument",
        "play",
        "plays",
        "guitar",
        "piano",
        "violin",
        "drums",
    ),
    "sport": ("sports", "exercise", "activity", "running", "tennis", "workout"),
    "suggest": ("suggested", "recommend", "recommended", "advised"),
    "sibling": ("brother", "sister", "family"),
    "sister": ("sibling", "brother", "family"),
    "son": ("child", "kid", "family", "parent", "mother", "father"),
    "symbolize": ("symbolized", "symbol", "represents", "meaning", "stands for"),
    "spouse": ("husband", "wife", "partner", "married", "marriage", "family"),
    "stay": ("stayed", "staying", "hotel", "place", "conference"),
    "support": ("supported", "supporting", "help", "helped"),
    "status": (
        "relationship",
        "parent",
        "breakup",
        "family",
        "kids",
        "friend",
        "support",
        "challenge",
        "dating",
        "partner",
        "married",
        "boyfriend",
        "girlfriend",
        "fiance",
        "fiancee",
        "engaged",
    ),
    "teammate": ("team", "colleague", "coworker", "work"),
    "task": ("todo", "to-do", "deadline", "finish", "complete", "due"),
    "text": ("texted", "message", "messaged", "sent"),
    "tell": ("told", "said", "mentioned"),
    "told": ("tell", "said", "mentioned"),
    "think": ("thought", "considered"),
    "travel": ("traveled", "travelled", "trip", "visited", "went", "country", "city"),
    "visit": ("visited", "visiting", "trip", "studio", "place", "event"),
    "vehicle": (
        "car",
        "vehicle",
        "drive",
        "drives",
        "driving",
        "own",
        "owns",
        "truck",
        "suv",
        "sedan",
        "van",
        "color",
    ),
    "want": (
        "wanted",
        "wants",
        "hoping",
        "hope",
        "planned",
        "goal",
        "future",
        "soon",
    ),
    "wife": ("spouse", "partner", "married", "marriage", "husband", "family"),
    "work": ("worked", "working", "job", "career"),
}
RELATION_QUERY_VARIANTS.update(
    {
        "activity": (
            "activities",
            "hobby",
            "hobbies",
            "partake",
            "do",
            "interest",
            "interests",
            "interesting",
            "class",
            "creative",
            "express",
            "therapeutic",
            "refresh",
            "fun",
            "pastime",
            "leisure",
        ),
        "adopt": (
            "adoption",
            "agency",
            "process",
            "family",
            "kids",
            "children",
        ),
        "adoption": (
            "adopt",
            "agency",
            "process",
            "family",
            "kids",
            "children",
            "lgbtq",
            "inclusive",
            "inclusivity",
        ),
        "agency": (
            "adoption",
            "adopt",
            "process",
            "individuals",
            "folks",
            "lgbtq",
            "inclusive",
            "inclusivity",
            "support",
            "help",
        ),
        "ally": ("support", "transgender", "lgbtq", "community", "advocate"),
        "choose": (
            "chose",
            "picked",
            "selected",
            "reason",
            "cause",
            "fit",
            "value",
            "spoke",
            "decide",
            "decision",
        ),
        "community": ("lgbtq", "transgender", "ally", "member", "support"),
        "counsel": ("counseling", "counselor", "mental", "health", "support"),
        "charity": ("race", "fundraiser", "awareness", "support"),
        "consider": (
            "considered",
            "considering",
            "looked at",
            "thinking",
        ),
        "decision": (
            "decide",
            "decided",
            "choice",
            "adopt",
            "adoption",
            "reaction",
            "response",
            "creating",
            "lovely",
            "luck",
        ),
        "excite": (
            "excited",
            "thrilled",
            "looking forward",
            "enthusiastic",
            "adoption",
            "family",
            "kids",
            "mom",
        ),
        "individual": ("individuals", "people", "lgbtq", "inclusive", "support"),
        "kid": (
            "kids",
            "children",
            "family",
            "preference",
            "interest",
            "like",
            "animals",
            "exhibit",
            "learning",
            "outdoors",
        ),
        "member": ("community", "lgbtq", "transgender", "ally", "belong"),
        "music": ("song", "composer", "piece", "instrumental", "orchestra"),
        "necklace": (
            "symbol",
            "meaning",
            "represents",
            "message",
            "value",
            "gift",
            "reminder",
            "family",
            "support",
            "special",
        ),
        "paint": ("painted", "painting", "image", "picture"),
        "park": (
            "national",
            "outdoor",
            "nature",
            "camping",
            "trip",
            "stories",
            "sky",
            "summer",
            "hike",
            "trail",
        ),
        "personality": (
            "traits",
            "concern",
            "thank",
            "care",
            "real",
            "help",
            "drive",
            "concern",
            "character",
            "describe",
            "quality",
            "impression",
        ),
        "plan": (
            "planned",
            "planning",
            "going to",
            "want",
            "summer",
            "dream",
            "family",
            "loving home",
            "kids",
            "future",
            "upcoming",
            "next",
            "goal",
        ),
        "process": (
            "adoption",
            "adopt",
            "make",
            "create",
            "family",
            "kids",
            "children",
        ),
        "race": ("ran", "running", "charity", "fundraiser", "awareness"),
        "realize": (
            "realized",
            "learned",
            "understood",
            "lesson",
            "reflection",
            "thought",
            "event",
            "journey",
        ),
        "roadtrip": (
            "road trip",
            "trip",
            "travel",
            "drive",
            "soon",
            "another",
        ),
        "school": ("speech", "event", "students", "talk", "presentation"),
        "self-care": (
            "wellness",
            "routine",
        "refresh",
        "present",
        "balance",
        "rest",
            "relax",
            "care",
        ),
        "song": ("piece", "composer", "instrumental", "orchestra", "fan"),
        "speech": ("school", "event", "students", "talk", "presentation"),
        "sunrise": ("paint", "painted", "painting", "image", "picture"),
        "support": (
            "supported",
            "supporting",
            "help",
            "helped",
            "lgbtq",
            "inclusive",
            "group",
        ),
        "summer": (
            "plans",
            "dream",
            "family",
            "loving home",
            "kids",
            "future",
            "upcoming",
            "next",
            "season",
            "goal",
        ),
        "think": ("thought", "considered", "opinion", "reaction", "response", "feel"),
        "trait": (
            "personality",
            "concern",
            "thank",
            "care",
            "real",
            "help",
            "drive",
            "character",
            "quality",
        ),
        "write": (
            "writing",
            "author",
            "draft",
            "story",
            "jobs",
        ),
    }
)
