"""Public API for the document_ingestion core feature."""

from __future__ import annotations

from infinity_context_core.features.document_ingestion.application import (
    DocumentIndexingStatus,
    DocumentIngestionUseCases,
    IngestDocumentCommand,
    IngestDocumentResult,
    IngestDocumentUseCase,
    PreparedDocumentIngestion,
    PrepareDocumentIngestionHandler,
    PrepareDocumentIngestionUseCase,
)
from infinity_context_core.features.document_ingestion.domain import (
    CHUNKING_POLICY_VERSION,
    FEATURE_ID,
    ChunkingPolicy,
    DocumentChunk,
    DocumentChunkDraft,
    DocumentChunkIdentity,
    DocumentChunkKind,
    DocumentChunkStatus,
    DocumentIngestionError,
    DocumentIngestionFeature,
    DocumentIngestionInvariantError,
    DocumentIngestionScope,
    DocumentIngestionValidationError,
    DocumentTextRange,
    SourceDocument,
    SourceDocumentClassification,
    SourceDocumentContent,
    SourceDocumentDraft,
    SourceDocumentIdentity,
    SourceDocumentOrigin,
    SourceDocumentStatus,
    content_hash_for_text,
    estimate_token_count,
    normalize_document_text,
)
from infinity_context_core.features.document_ingestion.ports import (
    DocumentChunkIndexItem,
    DocumentChunkIndexPort,
    DocumentChunkRepositoryPort,
    DocumentChunkUpsertResult,
    DocumentIndexingResult,
    SourceDocumentRepositoryPort,
)

__all__ = (
    "CHUNKING_POLICY_VERSION",
    "ChunkingPolicy",
    "DocumentChunk",
    "DocumentChunkDraft",
    "DocumentChunkIdentity",
    "DocumentChunkIndexItem",
    "DocumentChunkIndexPort",
    "DocumentChunkKind",
    "DocumentChunkRepositoryPort",
    "DocumentChunkStatus",
    "DocumentChunkUpsertResult",
    "DocumentIndexingResult",
    "DocumentIndexingStatus",
    "DocumentIngestionError",
    "DocumentIngestionFeature",
    "DocumentIngestionInvariantError",
    "DocumentIngestionScope",
    "DocumentIngestionUseCases",
    "DocumentIngestionValidationError",
    "DocumentTextRange",
    "FEATURE_ID",
    "IngestDocumentCommand",
    "IngestDocumentResult",
    "IngestDocumentUseCase",
    "PreparedDocumentIngestion",
    "PrepareDocumentIngestionHandler",
    "PrepareDocumentIngestionUseCase",
    "SourceDocument",
    "SourceDocumentClassification",
    "SourceDocumentContent",
    "SourceDocumentDraft",
    "SourceDocumentIdentity",
    "SourceDocumentOrigin",
    "SourceDocumentRepositoryPort",
    "SourceDocumentStatus",
    "content_hash_for_text",
    "estimate_token_count",
    "normalize_document_text",
)
