"""Narrow public API for provider-neutral cognitive memory foundations."""

from .application import (
    CanonicalEvidenceChangedCommand,
    InvalidateCognitiveDependenciesHandler,
    InvalidateCognitiveDependenciesResult,
    PersistCognitiveCandidateCommand,
    PersistCognitiveCandidateHandler,
    ProviderCognitiveDerivationUseCase,
)
from .domain import (
    FEATURE_ID,
    CanonicalEvidenceIdentity,
    CognitiveCandidate,
    CognitiveCandidateIdentity,
    CognitiveDerivationOrigin,
    CognitiveEvidenceRef,
    CognitiveKind,
    CognitiveMemoryFeature,
    CognitiveMemoryInvariantError,
    CognitiveProjectionDependencySet,
    CognitiveProjectionInvalidation,
    CognitiveProjectionState,
    CognitiveProjectionVersion,
    CognitiveScope,
    InvalidationAssessment,
    InvalidationDecision,
    PromotionAssessment,
    PromotionDecision,
    assess_invalidation,
    assess_promotion,
)
from .ports import (
    CognitiveDerivationDraft,
    CognitiveDerivationPort,
    CognitiveDerivationRequest,
    CognitiveDerivationSource,
    CognitiveProjectionRepositoryPort,
)

__all__ = (
    "FEATURE_ID",
    "CanonicalEvidenceIdentity",
    "CanonicalEvidenceChangedCommand",
    "CognitiveCandidate",
    "CognitiveCandidateIdentity",
    "CognitiveDerivationDraft",
    "CognitiveDerivationOrigin",
    "CognitiveDerivationPort",
    "CognitiveDerivationRequest",
    "CognitiveDerivationSource",
    "CognitiveEvidenceRef",
    "CognitiveKind",
    "CognitiveMemoryFeature",
    "CognitiveMemoryInvariantError",
    "CognitiveProjectionDependencySet",
    "CognitiveProjectionInvalidation",
    "CognitiveProjectionRepositoryPort",
    "CognitiveProjectionState",
    "CognitiveProjectionVersion",
    "CognitiveScope",
    "InvalidationAssessment",
    "InvalidationDecision",
    "InvalidateCognitiveDependenciesHandler",
    "InvalidateCognitiveDependenciesResult",
    "PersistCognitiveCandidateCommand",
    "PersistCognitiveCandidateHandler",
    "PromotionAssessment",
    "PromotionDecision",
    "ProviderCognitiveDerivationUseCase",
    "assess_invalidation",
    "assess_promotion",
)
