"""Public server seam for the memory_facts feature mirror."""

from __future__ import annotations

import infinity_context_core.features.memory_facts.public as memory_facts

from infinity_context_server.features.memory_facts.compatibility import (
    forget_fact_command_from_v1_path,
    legacy_interview_kind,
    legacy_interview_source,
    legacy_interview_speaker,
    legacy_interview_trust,
    link_fact_relation_command_from_v1_request,
    memory_kind_from_v1_request,
    remember_fact_command_from_v1_request,
    source_ref_from_v1_request,
    unlink_fact_relation_command_from_v1_path,
    update_fact_command_from_v1_request,
    validate_fact_status_filter,
)
from infinity_context_server.features.memory_facts.composition import (
    MemoryFactsServerComposition,
    MemoryFactsServerFeature,
    build_memory_facts_server_composition,
    build_memory_facts_server_feature,
)
from infinity_context_server.features.memory_facts.contracts import (
    ForgetFactHttpRequest,
    LinkFactRequest,
    MemoryFactSourceRefHttpRequest,
    RememberFactHttpRequest,
    RememberFactRequest,
    SourceRefRequest,
    UpdateFactHttpRequest,
    UpdateFactRequest,
)
from infinity_context_server.features.memory_facts.mappers import (
    evidence_ref_request_to_public,
    evidence_ref_to_response,
    fact_relation_item_to_response,
    fact_relation_to_response,
    fact_result_to_response,
    fact_to_response,
    forget_fact_command_from_http,
    forget_fact_request_to_command,
    forget_fact_result_to_contract,
    legacy_memory_fact_to_response,
    memory_fact_result_to_response,
    memory_fact_scope_from_contract,
    memory_fact_scope_from_ids,
    memory_fact_snapshot_to_contract,
    memory_fact_snapshot_to_response,
    related_fact_to_response,
    remember_fact_command_from_contract,
    remember_fact_request_to_command,
    remember_fact_result_to_contract,
    source_ref_request_to_public,
    source_ref_to_contract,
    source_ref_to_response,
    update_fact_command_from_http,
    update_fact_request_to_command,
    update_fact_result_to_contract,
    validate_fact_relation_status_filter,
)
from infinity_context_server.features.memory_facts.routes import (
    create_memory_facts_router,
)
from infinity_context_server.features.memory_facts.suggestion_requests import (
    CreateSuggestionBatchItemRequest,
    CreateSuggestionRequest,
    CreateSuggestionsBatchRequest,
    ResolveDuplicateMergeRequest,
    ResolveSuggestionConflictRequest,
    ReviewSuggestionBatchItemRequest,
    ReviewSuggestionRequest,
    ReviewSuggestionsBatchRequest,
    create_suggestion_command_from_v1_request,
    create_suggestions_batch_command_from_v1_request,
    normalize_suggestion_tag_filter,
    review_suggestions_batch_command_from_v1_request,
    validate_suggestion_confidence_and_trust,
    validate_suggestion_operation,
    validate_suggestion_review_action,
    validate_suggestion_status_filter,
)
from infinity_context_server.features.memory_facts.suggestion_responses import (
    create_suggestions_batch_to_response,
    review_suggestions_batch_to_response,
    suggestion_result_to_response,
    suggestion_to_response,
)

FEATURE_ID = memory_facts.FEATURE_ID

__all__ = (
    "CreateSuggestionBatchItemRequest",
    "CreateSuggestionRequest",
    "CreateSuggestionsBatchRequest",
    "ForgetFactHttpRequest",
    "LinkFactRequest",
    "MemoryFactSourceRefHttpRequest",
    "MemoryFactsServerComposition",
    "MemoryFactsServerFeature",
    "RememberFactRequest",
    "RememberFactHttpRequest",
    "ResolveDuplicateMergeRequest",
    "ResolveSuggestionConflictRequest",
    "ReviewSuggestionBatchItemRequest",
    "ReviewSuggestionRequest",
    "ReviewSuggestionsBatchRequest",
    "SourceRefRequest",
    "UpdateFactRequest",
    "UpdateFactHttpRequest",
    "FEATURE_ID",
    "build_memory_facts_server_composition",
    "build_memory_facts_server_feature",
    "create_memory_facts_router",
    "create_suggestion_command_from_v1_request",
    "create_suggestions_batch_to_response",
    "create_suggestions_batch_command_from_v1_request",
    "evidence_ref_request_to_public",
    "evidence_ref_to_response",
    "fact_relation_item_to_response",
    "fact_relation_to_response",
    "fact_result_to_response",
    "fact_to_response",
    "forget_fact_command_from_v1_path",
    "forget_fact_command_from_http",
    "forget_fact_request_to_command",
    "forget_fact_result_to_contract",
    "legacy_interview_kind",
    "legacy_interview_source",
    "legacy_interview_speaker",
    "legacy_interview_trust",
    "legacy_memory_fact_to_response",
    "link_fact_relation_command_from_v1_request",
    "memory_kind_from_v1_request",
    "memory_fact_result_to_response",
    "memory_fact_scope_from_contract",
    "memory_fact_scope_from_ids",
    "memory_fact_snapshot_to_contract",
    "memory_fact_snapshot_to_response",
    "normalize_suggestion_tag_filter",
    "related_fact_to_response",
    "remember_fact_command_from_v1_request",
    "remember_fact_command_from_contract",
    "remember_fact_request_to_command",
    "remember_fact_result_to_contract",
    "review_suggestions_batch_command_from_v1_request",
    "review_suggestions_batch_to_response",
    "source_ref_from_v1_request",
    "source_ref_request_to_public",
    "source_ref_to_contract",
    "source_ref_to_response",
    "suggestion_result_to_response",
    "suggestion_to_response",
    "unlink_fact_relation_command_from_v1_path",
    "update_fact_command_from_v1_request",
    "update_fact_command_from_http",
    "update_fact_request_to_command",
    "update_fact_result_to_contract",
    "validate_fact_status_filter",
    "validate_fact_relation_status_filter",
    "validate_suggestion_confidence_and_trust",
    "validate_suggestion_operation",
    "validate_suggestion_review_action",
    "validate_suggestion_status_filter",
)
