"""Bundle diagnostic key sets and default counters."""

from __future__ import annotations

_BUNDLE_COUNTER_KEYS = (
    "facts_considered",
    "anchors_considered",
    "anchor_lookup_keys_considered",
    "anchors_loaded_by_lookup",
    "anchors_used",
    "anchors_used_by_query_intent",
    "anchors_dropped_by_query_intent_conflict",
    "anchor_relation_candidates_considered",
    "anchor_relation_items_used",
    "query_anchor_hint_count",
    "query_anchor_person_hint_count",
    "query_anchor_event_hint_count",
    "query_anchor_project_hint_count",
    "query_anchor_organization_hint_count",
    "query_anchor_temporal_hint_count",
    "query_anchor_event_type_hint_count",
    "keyword_chunks_considered",
    "keyword_query_count",
    "keyword_chunks_dropped_by_relevance",
    "keyword_neighbor_chunks_considered",
    "keyword_neighbor_chunks_used",
    "keyword_neighbor_chunks_skipped",
    "keyword_source_sibling_chunks_considered",
    "keyword_source_sibling_chunks_used",
    "keyword_source_sibling_chunks_skipped",
    "keyword_source_sibling_group_count",
    "keyword_source_sibling_candidate_limit",
    "keyword_aggregation_chunks_considered",
    "keyword_aggregation_chunks_used",
    "keyword_aggregation_chunks_skipped",
    "keyword_aggregation_relaxed_relevance_used",
    "keyword_aggregation_slot_reservations_used",
    "keyword_aggregation_source_families_used",
    "keyword_aggregation_numeric_corroborations",
    "keyword_aggregation_distinct_member_candidates",
    "keyword_aggregation_distinct_member_reservations_used",
    "keyword_aggregation_distinct_member_slots_used",
    "keyword_aggregation_chunks_deduplicated",
    "keyword_aggregation_admitted_not_selected",
    "keyword_aggregation_continuity_items_used",
    "keyword_aggregation_continuity_limit",
    "keyword_aggregation_continuity_items_promoted",
    "keyword_aggregation_continuity_items_suppressed",
    "keyword_aggregation_admission_queries",
    "keyword_aggregation_admission_seed_chunks",
    "keyword_aggregation_admission_seed_chunks_added",
    "pre_rerank_distinct_set_evidence_items_considered",
    "pre_rerank_distinct_set_evidence_bodies_restored",
    "pre_rerank_distinct_set_evidence_items_added_for_rerank",
    "pre_rerank_distinct_set_evidence_items_rejected_before_rerank",
    "distinct_set_evidence_items_considered",
    "distinct_set_evidence_bodies_restored",
    "distinct_set_evidence_items_readded",
    "distinct_set_evidence_items_missing_after_ranking",
    "distinct_set_evidence_items_rejected_by_rerank",
    "distinct_set_candidates_considered",
    "distinct_set_source_candidates",
    "distinct_set_items_selected",
    "distinct_set_member_slots_selected",
    "distinct_set_redundant_items_suppressed",
    "vector_query_count",
    "vector_embedding_vector_count",
    "vector_search_count",
    "vector_query_limit",
    "vector_query_degraded_count",
    "vector_candidate_count",
    "vector_hydrated_count",
    "graph_query_count",
    "graph_query_limit",
    "graph_query_degraded_count",
    "graph_candidate_count",
    "graph_hydrated_count",
    "rag_query_count",
    "rag_query_limit",
    "rag_candidate_count",
    "rag_hydrated_count",
    "rag_query_degraded_count",
    "artifact_evidence_jobs_considered",
    "artifact_evidence_manifests_considered",
    "artifact_evidence_manifests_used",
    "artifact_evidence_items_considered",
    "artifact_evidence_items_used",
    "artifact_evidence_ranked_candidate_count",
    "artifact_evidence_candidate_cap_reached_count",
    "artifact_evidence_confidence_signal_count",
    "artifact_evidence_coordinate_signal_count",
    "artifact_evidence_time_query_count",
    "artifact_evidence_time_query_match_count",
    "artifact_evidence_time_query_drop_count",
    "artifact_evidence_invalid_time_range_count",
    "artifact_evidence_invalid_bbox_count",
    "artifact_evidence_visual_region_query_drop_count",
    "artifact_evidence_document_location_query_drop_count",
    "artifact_evidence_extracted_text_query_drop_count",
    "artifact_evidence_query_drop_count",
    "artifact_evidence_sensitive_drop_count",
    "artifact_evidence_prompt_injection_drop_count",
    "artifact_evidence_manifest_too_large_count",
    "artifact_evidence_read_error_count",
    "artifact_evidence_parse_error_count",
    "artifact_evidence_schema_skip_count",
    "artifact_evidence_stale_asset_drop_count",
    "stale_vector_drop_count",
    "stale_graph_drop_count",
    "stale_rag_drop_count",
    "stale_facts_considered",
    "stale_facts_used",
    "superseded_facts_considered",
    "superseded_facts_used",
    "temporal_relations_considered",
    "temporal_replacements_applied",
    "temporal_contradictions_considered",
    "temporal_relations_skipped_by_validity",
    "linked_temporal_relations_considered",
    "linked_temporal_replacements_applied",
    "linked_temporal_contradictions_considered",
    "linked_temporal_relations_skipped_by_validity",
    "pending_conflict_suggestions_considered",
    "pending_duplicate_merge_suggestions_considered",
    "approved_context_links_considered",
    "approved_context_links_used",
    "approved_context_linked_chunks_used",
    "approved_context_linked_facts_used",
    "approved_context_linked_anchors_used",
    "approved_context_linked_assets_used",
    "approved_context_linked_asset_manifest_jobs_considered",
    "approved_context_linked_asset_manifest_artifacts_considered",
    "approved_context_linked_asset_manifest_items_used",
    "approved_context_linked_asset_manifest_blob_storage_disabled_count",
    "approved_context_linked_asset_manifest_too_large_count",
    "approved_context_linked_asset_manifest_read_error_count",
    "approved_context_linked_asset_manifest_parse_error_count",
    "approved_context_linked_asset_manifest_schema_skip_count",
    "approved_context_linked_extraction_artifacts_used",
    "approved_context_linked_extraction_artifact_manifest_items_used",
    "approved_context_linked_extraction_artifact_blob_storage_disabled_count",
    "approved_context_linked_extraction_artifact_manifest_too_large_count",
    "approved_context_linked_extraction_artifact_read_error_count",
    "approved_context_linked_extraction_artifact_parse_error_count",
    "approved_context_linked_extraction_artifact_schema_skip_count",
    "stale_context_linked_chunk_drop_count",
    "stale_context_linked_fact_drop_count",
    "stale_context_linked_anchor_drop_count",
    "stale_context_linked_asset_drop_count",
    "stale_context_linked_extraction_artifact_drop_count",
    "final_rank_source_item_count",
    "final_rank_candidate_item_count",
    "hybrid_items_used",
    "items_considered",
    "items_used",
    "diversity_families_considered",
    "diversity_families_used",
    "diversity_items_used",
    "answer_support_families_considered",
    "answer_support_families_used",
    "answer_support_items_used",
    "chunk_sources_considered",
    "chunk_sources_used",
    "max_chunks_used_per_source",
    "source_capped_sources_considered",
    "source_capped_sources_used",
    "max_source_capped_items_used_per_source",
    "source_diversity_chunks_reordered",
    "dropped_by_instruction_flag",
    "dropped_by_budget",
    "dropped_by_source_cap",
    "dropped_by_source_group_cap",
    "dropped_by_char_cap",
    "citations_rendered",
    "citation_quote_previews_rendered",
    "sensitive_citation_quote_previews_skipped",
    "sensitive_source_identity_parts_redacted",
    "unsafe_source_identity_parts_sanitized",
    "sensitive_item_text_redacted",
    "multimodal_source_ref_count",
    "items_with_multimodal_source_refs",
    "source_refs_with_page_count",
    "source_refs_with_bbox_count",
    "source_refs_with_time_range_count",
    "source_refs_with_char_range_count",
    "query_snippet_items_used",
    "query_snippet_source_refs_enriched",
    "media_time_query_items_used",
    "media_time_query_matched_items_used",
    "requirement_guard_items_considered",
    "requirement_guard_items_dropped",
    "rendered_chars",
    "max_rendered_chars",
)
_BUNDLE_COUNTER_DEFAULTS = {
    "facts_considered": 0,
    "anchors_considered": 0,
    "anchor_lookup_keys_considered": 0,
    "anchors_loaded_by_lookup": 0,
    "anchors_used": 0,
    "anchors_used_by_query_intent": 0,
    "anchors_dropped_by_query_intent_conflict": 0,
    "anchor_relation_candidates_considered": 0,
    "anchor_relation_items_used": 0,
    "query_anchor_hint_count": 0,
    "query_anchor_person_hint_count": 0,
    "query_anchor_event_hint_count": 0,
    "query_anchor_project_hint_count": 0,
    "query_anchor_organization_hint_count": 0,
    "query_anchor_temporal_hint_count": 0,
    "query_anchor_event_type_hint_count": 0,
    "keyword_chunks_considered": 0,
    "keyword_query_count": 0,
    "keyword_chunks_dropped_by_relevance": 0,
    "keyword_neighbor_chunks_considered": 0,
    "keyword_neighbor_chunks_used": 0,
    "keyword_neighbor_chunks_skipped": 0,
    "keyword_source_sibling_chunks_considered": 0,
    "keyword_source_sibling_chunks_used": 0,
    "keyword_source_sibling_chunks_skipped": 0,
    "keyword_source_sibling_group_count": 0,
    "keyword_source_sibling_candidate_limit": 0,
    "keyword_aggregation_chunks_considered": 0,
    "keyword_aggregation_chunks_used": 0,
    "keyword_aggregation_chunks_skipped": 0,
    "vector_query_count": 0,
    "vector_embedding_vector_count": 0,
    "vector_search_count": 0,
    "vector_query_limit": 0,
    "vector_query_degraded_count": 0,
    "vector_candidate_count": 0,
    "vector_hydrated_count": 0,
    "graph_query_count": 0,
    "graph_query_limit": 0,
    "graph_query_degraded_count": 0,
    "graph_candidate_count": 0,
    "graph_hydrated_count": 0,
    "rag_query_count": 0,
    "rag_query_limit": 0,
    "rag_candidate_count": 0,
    "rag_hydrated_count": 0,
    "rag_query_degraded_count": 0,
    "artifact_evidence_jobs_considered": 0,
    "artifact_evidence_manifests_considered": 0,
    "artifact_evidence_manifests_used": 0,
    "artifact_evidence_items_considered": 0,
    "artifact_evidence_items_used": 0,
    "artifact_evidence_ranked_candidate_count": 0,
    "artifact_evidence_candidate_cap_reached_count": 0,
    "artifact_evidence_confidence_signal_count": 0,
    "artifact_evidence_coordinate_signal_count": 0,
    "artifact_evidence_time_query_count": 0,
    "artifact_evidence_time_query_match_count": 0,
    "artifact_evidence_time_query_drop_count": 0,
    "artifact_evidence_invalid_time_range_count": 0,
    "artifact_evidence_invalid_bbox_count": 0,
    "artifact_evidence_visual_region_query_drop_count": 0,
    "artifact_evidence_document_location_query_drop_count": 0,
    "artifact_evidence_extracted_text_query_drop_count": 0,
    "artifact_evidence_query_drop_count": 0,
    "artifact_evidence_sensitive_drop_count": 0,
    "artifact_evidence_prompt_injection_drop_count": 0,
    "artifact_evidence_manifest_too_large_count": 0,
    "artifact_evidence_read_error_count": 0,
    "artifact_evidence_parse_error_count": 0,
    "artifact_evidence_schema_skip_count": 0,
    "artifact_evidence_stale_asset_drop_count": 0,
    "stale_vector_drop_count": 0,
    "stale_graph_drop_count": 0,
    "stale_rag_drop_count": 0,
    "temporal_relations_considered": 0,
    "temporal_replacements_applied": 0,
    "temporal_contradictions_considered": 0,
    "temporal_relations_skipped_by_validity": 0,
    "linked_temporal_relations_considered": 0,
    "linked_temporal_replacements_applied": 0,
    "linked_temporal_contradictions_considered": 0,
    "linked_temporal_relations_skipped_by_validity": 0,
    "stale_facts_considered": 0,
    "stale_facts_used": 0,
    "superseded_facts_considered": 0,
    "superseded_facts_used": 0,
    "pending_conflict_suggestions_considered": 0,
    "pending_duplicate_merge_suggestions_considered": 0,
    "approved_context_links_considered": 0,
    "approved_context_links_used": 0,
    "approved_context_linked_chunks_used": 0,
    "approved_context_linked_facts_used": 0,
    "approved_context_linked_anchors_used": 0,
    "approved_context_linked_assets_used": 0,
    "approved_context_linked_asset_manifest_jobs_considered": 0,
    "approved_context_linked_asset_manifest_artifacts_considered": 0,
    "approved_context_linked_asset_manifest_items_used": 0,
    "approved_context_linked_asset_manifest_blob_storage_disabled_count": 0,
    "approved_context_linked_asset_manifest_too_large_count": 0,
    "approved_context_linked_asset_manifest_read_error_count": 0,
    "approved_context_linked_asset_manifest_parse_error_count": 0,
    "approved_context_linked_asset_manifest_schema_skip_count": 0,
    "approved_context_linked_extraction_artifacts_used": 0,
    "approved_context_linked_extraction_artifact_manifest_items_used": 0,
    "approved_context_linked_extraction_artifact_blob_storage_disabled_count": 0,
    "approved_context_linked_extraction_artifact_manifest_too_large_count": 0,
    "approved_context_linked_extraction_artifact_read_error_count": 0,
    "approved_context_linked_extraction_artifact_parse_error_count": 0,
    "approved_context_linked_extraction_artifact_schema_skip_count": 0,
    "stale_context_linked_chunk_drop_count": 0,
    "stale_context_linked_fact_drop_count": 0,
    "stale_context_linked_anchor_drop_count": 0,
    "stale_context_linked_asset_drop_count": 0,
    "stale_context_linked_extraction_artifact_drop_count": 0,
    "hybrid_items_used": 0,
    "items_considered": 0,
    "items_used": 0,
    "diversity_families_considered": 0,
    "diversity_families_used": 0,
    "diversity_items_used": 0,
    "answer_support_families_considered": 0,
    "answer_support_families_used": 0,
    "answer_support_items_used": 0,
    "chunk_sources_considered": 0,
    "chunk_sources_used": 0,
    "max_chunks_used_per_source": 0,
    "source_capped_sources_considered": 0,
    "source_capped_sources_used": 0,
    "max_source_capped_items_used_per_source": 0,
    "source_diversity_chunks_reordered": 0,
    "dropped_by_instruction_flag": 0,
    "dropped_by_budget": 0,
    "dropped_by_source_cap": 0,
    "dropped_by_source_group_cap": 0,
    "dropped_by_char_cap": 0,
    "citations_rendered": 0,
    "citation_quote_previews_rendered": 0,
    "sensitive_citation_quote_previews_skipped": 0,
    "sensitive_source_identity_parts_redacted": 0,
    "unsafe_source_identity_parts_sanitized": 0,
    "sensitive_item_text_redacted": 0,
    "multimodal_source_ref_count": 0,
    "items_with_multimodal_source_refs": 0,
    "source_refs_with_page_count": 0,
    "source_refs_with_bbox_count": 0,
    "source_refs_with_time_range_count": 0,
    "source_refs_with_char_range_count": 0,
    "query_snippet_items_used": 0,
    "query_snippet_source_refs_enriched": 0,
    "media_time_query_items_used": 0,
    "media_time_query_matched_items_used": 0,
    "requirement_guard_items_considered": 0,
    "requirement_guard_items_dropped": 0,
    "rendered_chars": 0,
    "max_rendered_chars": 0,
}
_BUNDLE_STATUS_DEFAULTS = {
    "vector_status": "unknown",
    "graph_status": "unknown",
    "rag_status": "unknown",
    "artifact_evidence_status": "unknown",
    "requirement_guard_status": "not_triggered",
}
_BUNDLE_PROVIDER_STATUS_TEXT_KEYS = (
    "vector_degraded_reason",
    "vector_degraded_step",
    "vector_skip_reason",
    "graph_degraded_reason",
    "graph_degraded_step",
    "graph_skip_reason",
    "rag_degraded_reason",
    "rag_degraded_step",
    "rag_skip_reason",
)
_BUNDLE_PROVIDER_STATUS_FLOAT_KEYS = (
    "vector_deadline_seconds",
    "graph_deadline_seconds",
    "rag_deadline_seconds",
)
_BUNDLE_QUERY_ANCHOR_TEXT_KEYS = (
    "query_anchor_intent_status",
)
_BUNDLE_QUERY_ANCHOR_LIST_KEYS = (
    "query_anchor_hint_reasons",
)
_BUNDLE_KEYWORD_AGGREGATION_TEXT_KEYS = (
    "keyword_aggregation_query_kind",
)
_BUNDLE_KEYWORD_AGGREGATION_MAPPING_KEYS = (
    "keyword_aggregation_admission_reasons",
)
_BUNDLE_QUERY_PLAN_TEXT_KEYS = (
    "query_expansion_status",
    "query_decomposition_status",
)
_BUNDLE_QUERY_PLAN_COUNTER_KEYS = (
    "query_expansion_count",
    "query_decomposition_count",
)
_BUNDLE_QUERY_PLAN_LIST_KEYS = (
    "keyword_query_reasons",
    "query_expansion_reasons",
    "query_decomposition_reasons",
)
_BUNDLE_TEMPORAL_QUERY_TEXT_KEYS = (
    "temporal_query_intent_status",
)
_BUNDLE_TEMPORAL_QUERY_BOOL_KEYS = (
    "temporal_query_prefers_current",
    "temporal_query_requests_previous",
    "temporal_query_requests_change",
    "temporal_query_after_event",
    "temporal_query_before_event",
    "temporal_query_excludes_stale",
    "temporal_query_include_superseded_review",
)
_BUNDLE_TEMPORAL_QUERY_LIST_KEYS = (
    "temporal_query_intent_reasons",
    "temporal_query_relative_time_hints",
)
