"""Compatibility facade for reason-specific context ranking policies."""

from __future__ import annotations

from infinity_context_core.application.context_ranking_reason_priorities import (
    ACTIVITY_OBSERVATION_SOURCE_REASONS,
    ACTIVITY_OWNER_REASONS,
    CONTEXT_ITEM_REASON_PRIORITY,
    DERIVED_SUMMARY_SOURCE_MIN_DISTINCTIVE_HITS,
    DERIVED_SUMMARY_SOURCE_REASONS,
    PRECISE_TURN_SOURCE_SIBLING_REASONS,
    QUERY_REASON_PRIORITY,
    QUERY_REASON_PRIORITY_MIN_DISTINCTIVE_HITS,
)
from infinity_context_core.application.context_ranking_reason_scores import (
    KEYWORD_EXPANSION_REASON_BOOSTS,
    KEYWORD_EXPANSION_SCORE_CAPS,
)

__all__ = [
    "ACTIVITY_OBSERVATION_SOURCE_REASONS",
    "ACTIVITY_OWNER_REASONS",
    "CONTEXT_ITEM_REASON_PRIORITY",
    "DERIVED_SUMMARY_SOURCE_MIN_DISTINCTIVE_HITS",
    "DERIVED_SUMMARY_SOURCE_REASONS",
    "KEYWORD_EXPANSION_REASON_BOOSTS",
    "KEYWORD_EXPANSION_SCORE_CAPS",
    "PRECISE_TURN_SOURCE_SIBLING_REASONS",
    "QUERY_REASON_PRIORITY",
    "QUERY_REASON_PRIORITY_MIN_DISTINCTIVE_HITS",
]
