"""Public API for the memory_scopes core feature."""

from __future__ import annotations

from infinity_context_core.features.memory_scopes.application import (
    CreateMemoryScopeCommand,
    CreateMemoryScopeHandler,
    CreateMemoryScopeResult,
    CreateMemoryScopeUseCase,
    DuplicateMemoryScopeExternalRefError,
    MemoryScopeApplicationError,
    MemoryScopeConflictError,
    MemoryScopeNotFoundError,
    MemoryScopeUseCases,
    TransferMemoryScopeOwnershipCommand,
    TransferMemoryScopeOwnershipHandler,
    TransferMemoryScopeOwnershipResult,
    TransferMemoryScopeOwnershipUseCase,
)
from infinity_context_core.features.memory_scopes.domain import (
    FEATURE_ID,
    MEMORY_SCOPE_ADMIN_CAPABILITY,
    MEMORY_SCOPE_STATUS_ACTIVE,
    MEMORY_SCOPE_STATUS_ARCHIVED,
    MEMORY_SCOPE_STATUS_DELETED,
    MEMORY_SCOPE_TRANSFER_CAPABILITY,
    VALID_MEMORY_SCOPE_STATUSES,
    MemoryScopeActor,
    MemoryScopeCapability,
    MemoryScopeDomainError,
    MemoryScopeIdentity,
    MemoryScopeOwner,
    MemoryScopeOwnershipDecision,
    MemoryScopeOwnershipError,
    MemoryScopeOwnershipPolicy,
    MemoryScopePrincipalKind,
    MemoryScopeSnapshot,
    MemoryScopeStatus,
    MemoryScopesFeature,
)
from infinity_context_core.features.memory_scopes.ports import (
    MemoryScopeClockPort,
    MemoryScopeIdPort,
    MemoryScopeRepositoryPort,
    MemoryScopeUnitOfWorkFactoryPort,
    MemoryScopeUnitOfWorkPort,
)

__all__ = (
    "FEATURE_ID",
    "MEMORY_SCOPE_ADMIN_CAPABILITY",
    "MEMORY_SCOPE_STATUS_ACTIVE",
    "MEMORY_SCOPE_STATUS_ARCHIVED",
    "MEMORY_SCOPE_STATUS_DELETED",
    "MEMORY_SCOPE_TRANSFER_CAPABILITY",
    "CreateMemoryScopeCommand",
    "CreateMemoryScopeHandler",
    "CreateMemoryScopeResult",
    "CreateMemoryScopeUseCase",
    "DuplicateMemoryScopeExternalRefError",
    "MemoryScopeActor",
    "MemoryScopeApplicationError",
    "MemoryScopeCapability",
    "MemoryScopeClockPort",
    "MemoryScopeConflictError",
    "MemoryScopeDomainError",
    "MemoryScopeIdPort",
    "MemoryScopeIdentity",
    "MemoryScopeNotFoundError",
    "MemoryScopeOwner",
    "MemoryScopeOwnershipDecision",
    "MemoryScopeOwnershipError",
    "MemoryScopeOwnershipPolicy",
    "MemoryScopePrincipalKind",
    "MemoryScopeRepositoryPort",
    "MemoryScopeSnapshot",
    "MemoryScopeStatus",
    "MemoryScopeUnitOfWorkFactoryPort",
    "MemoryScopeUnitOfWorkPort",
    "MemoryScopeUseCases",
    "MemoryScopesFeature",
    "TransferMemoryScopeOwnershipCommand",
    "TransferMemoryScopeOwnershipHandler",
    "TransferMemoryScopeOwnershipResult",
    "TransferMemoryScopeOwnershipUseCase",
    "VALID_MEMORY_SCOPE_STATUSES",
)
